# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import memory_game_pb2 as memory__game__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in memory_game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryGameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinGame = channel.unary_unary(
                '/memorygame.MemoryGame/JoinGame',
                request_serializer=memory__game__pb2.PlayerInfo.SerializeToString,
                response_deserializer=memory__game__pb2.PlayerId.FromString,
                _registered_method=True)
        self.PlayTurn = channel.unary_unary(
                '/memorygame.MemoryGame/PlayTurn',
                request_serializer=memory__game__pb2.TurnRequest.SerializeToString,
                response_deserializer=memory__game__pb2.TurnResponse.FromString,
                _registered_method=True)
        self.GetBoardState = channel.unary_unary(
                '/memorygame.MemoryGame/GetBoardState',
                request_serializer=memory__game__pb2.PlayerId.SerializeToString,
                response_deserializer=memory__game__pb2.BoardState.FromString,
                _registered_method=True)
        self.SubscribeToUpdates = channel.unary_stream(
                '/memorygame.MemoryGame/SubscribeToUpdates',
                request_serializer=memory__game__pb2.PlayerId.SerializeToString,
                response_deserializer=memory__game__pb2.BoardState.FromString,
                _registered_method=True)


class MemoryGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinGame(self, request, context):
        """Unirse al juego con un nombre, devuelve un ID único
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayTurn(self, request, context):
        """Enviar una jugada (2 coordenadas) al servidor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBoardState(self, request, context):
        """Obtener el estado actual del tablero
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToUpdates(self, request, context):
        """Suscripción a actualizaciones en tiempo real del juego
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=memory__game__pb2.PlayerInfo.FromString,
                    response_serializer=memory__game__pb2.PlayerId.SerializeToString,
            ),
            'PlayTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayTurn,
                    request_deserializer=memory__game__pb2.TurnRequest.FromString,
                    response_serializer=memory__game__pb2.TurnResponse.SerializeToString,
            ),
            'GetBoardState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBoardState,
                    request_deserializer=memory__game__pb2.PlayerId.FromString,
                    response_serializer=memory__game__pb2.BoardState.SerializeToString,
            ),
            'SubscribeToUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToUpdates,
                    request_deserializer=memory__game__pb2.PlayerId.FromString,
                    response_serializer=memory__game__pb2.BoardState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memorygame.MemoryGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memorygame.MemoryGame', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryGame(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memorygame.MemoryGame/JoinGame',
            memory__game__pb2.PlayerInfo.SerializeToString,
            memory__game__pb2.PlayerId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memorygame.MemoryGame/PlayTurn',
            memory__game__pb2.TurnRequest.SerializeToString,
            memory__game__pb2.TurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBoardState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memorygame.MemoryGame/GetBoardState',
            memory__game__pb2.PlayerId.SerializeToString,
            memory__game__pb2.BoardState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/memorygame.MemoryGame/SubscribeToUpdates',
            memory__game__pb2.PlayerId.SerializeToString,
            memory__game__pb2.BoardState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
